# Generated by Django 5.1 on 2024-09-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eac_api', '0003_remove_student_user_name_alter_student_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
