# Generated by Django 5.1 on 2024-09-04 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eac_api', '0004_alter_student_email_alter_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.IntegerField(blank=True, default=2020),
        ),
        migrations.AddField(
            model_name='student',
            name='bio',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='student',
            name='instution',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='subject',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
