# Generated by Django 5.1 on 2024-09-04 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eac_api', '0005_student_batch_student_bio_student_date_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='student',
            managers=[
            ],
        ),
    ]
